name: Main

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+.rc[0-9]+'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: adya/pack-skse-mod/.github/workflows/pack.yml@dev
    with:
      CMAKE_SE_BUILD_PRESET: 'vs2022-windows-vcpkg-se'
      CMAKE_AE_BUILD_PRESET: 'vs2022-windows-vcpkg-ae'
      CMAKE_VR_CONFIG_PRESET: ''
      CMAKE_VR_BUILD_PRESET: ''
      FOMOD_INCLUDE_PDB: true
      FOMOD_REQUIRED_INSTALLATION_DIR: "FOMOD/Required Files"
      FOMOD_MOD_NAME: "Player Name Randomizer"
      FOMOD_MOD_AUTHOR: "sasnikol"
      FOMOD_MOD_NEXUS_ID: "92438"
      FOMOD_DEFAULT_IMAGE: "FOMOD/images/cover.png"